# Generated by Django 4.2 on 2025-02-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_registration_email_alter_registration_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='transactionid',
            field=models.CharField(default='transactionid', max_length=100),
        ),
    ]
