runtime: python39

handlers:
- url: /static
  static_dir: static/
- url: /media
  static_dir: media/

env_variables:
  DJANGO_SETTINGS_MODULE: "tech.settings"

entrypoint: waitress-serve --listen=0.0.0.0:$PORT tech.wsgi:application
